name: 'Deploy to AWS S3'
description: 'Deploy built JavaScript files to an AWS S3 bucket.'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
    type: string
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
    type: string 
  aws-region:
    description: 'AWS Region'
    required: false
    default: 'us-east-1'
    type: string  
  bucket-name:
    description: 'S3 Bucket Name'
    required: true
    type: string
  source-dir:
    description: 'Folder containing built JavaScript files'
    required: true
    type: string

runs:
  using: 'node24'
  main: 'index.js'