name: 'Custom Composite Action with Cached Dependencies'
description: 'A Composite Action that caches dependencies and runs a custom script.'
inputs:
  caching:
    description: 'Whether or not to cache dependencies.'
    required: true
    type: boolean
    
outputs:
  cache-status:
    description: 'Whether the cache was used or not.'
    value: ${{ steps.install-deps.outputs.cache-used }}

runs:
  using: 'composite'
  steps:
    - name: Cache Node.js modules
      if: ${{ inputs.caching == 'true' }}
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  
    - name: Install dependencies
      id: install-deps
      if: steps.cache-node-modules.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: | 
        npm ci
        echo "cache-used='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash