name: Reusable Workflow
on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '20'
      artifact-name:
        description: 'Name of the artifact to upload'
        required: true
        type: string
        default: 'build-artifact'
   
    outputs:
      workflow-result:
        description: 'Job output from build job'
        value: ${{ jobs.build.outputs.build-output }}

    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-output: ${{ steps.set-output.outputs.build-result }}
    steps:
      - name: Calling out to reusable workflow
        run: echo "This step is just a placeholder"
      - name: Artifact Name
        run: echo "Artifact name is ${{ inputs.artifact-name }}"
      - name: Reusable Input secrets
        run: echo "NPM Token is ${{ secrets.NPM_TOKEN }}"
      - name: Set Result Output
        id: set-output
        run: echo "build-result=SUCCESS" >> $GITHUB_OUTPUT
      # - name: Authenticate to npm registry
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build project
      #   run: npm run build
      # - name: Output script file path
      #   id: publish-name
      #   run: echo "script-file=dist/index.js" >> $GITHUB_OUTPUT