name: Test Action
on:
  push:
    branches:
      - dev
    paths:
      - '**.ts'
      - '**.js'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/**'
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    branches:
      - main
  issues:
    types: [opened, edited, reopened]
  # schedule:
  #   - cron: '0 0 * * 0' # Runs every Sunday at midnight

env:
  NODE_ENV: development
  CI: true
  ENV_LEVEL: WORKFLOW

jobs:
  test:
    container: # Use a container to run the job
      image: node:20 # Use the official Node.js 20 image
      options: --user node
    env:
      NODE_ENV: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v5
      # - name: Set up Node.js
      #   uses: actions/setup-node@v5
      #   with:
      #     node-version: '20'
      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Echo Environment Variables
        run: echo "ENV_LEVEL is set to $ENV_LEVEL and NODE_ENV is set to ${{ env.NODE_ENV }}"
  build:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20, 18]
        include:
          - os: ubuntu-latest
            node-version: 16
        exclude:
          - os: windows-latest
            node-version: 18
    needs: test
    runs-on: ${{ matrix.os }} #ubuntu-latest
    outputs:
      script-file: ${{ steps.publish-name.outputs.script-file }}
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  
      - name: Echo OS info
        run: uname -a
      - name: Echo Runner info
        run: echo $RUNNER_OS
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Publish JS filename
        id: publish-name
        run: find dist/src/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          # path: |
          #   dist/**
          #   .github/workflows/**
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Show artifacts content
        run: ls
      - name: Use exported built script file
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy to Production
        run: echo "Deploying to production server..."

  reusable-workflow:
    needs: build
    uses: ./.github/workflows/reusable.yml
    with:
      node-version: '20'
      artifact-name: 'build-artifacts'
    secrets:
      NPM_TOKEN: "NPM-SECRET-VALUE"

  workflow-result:
    needs: reusable-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Get reusable workflow output
        run: echo "Reusable workflow result ${{ needs.reusable-workflow.outputs.workflow-result }}"
  report:
    name: Report Job Status
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Job Status
        run: echo "The job has completed with status ${{ job.status }}"
  
